# === HYPRLPAPER ===
# Este arquivo é fallback — o wallpaper.sh prefere usar SWWW
# Edite SEU_USUARIO se for usar hyprpaper direto

preload = /home/SEU_USUARIO/Pictures/Wallpapers/guts.png
wallpaper = ,/home/SEU_USUARIO/Pictures/Wallpapers/guts.png
splash = false
ipc = on
