# 1. Dar o "preload" nas imagens com a extensão e usuário corretos
preload = /home/seus/Imagens/Wallpapers/guts.png
preload = /home/seus/Imagens/Wallpapers/default.png

# 2. Definir o alvo (target) para cada monitor especificamente
wallpaper = DP-3,/home/seus/Imagens/Wallpapers/guts.png
wallpaper = HDMI-A-1,/home/seus/Imagens/Wallpapers/default.png

# 3. Opções de performance
splash = false
ipc = on

