preload = ~/Pictures/Wallpapers/guts.png
preload = ~/Pictures/Wallpapers/default.png
preload = ~/Pictures/Wallpapers/default.jpg

wallpaper = DP-3,~/Pictures/Wallpapers/guts.png
wallpaper = HDMI-A-1,~/Pictures/Wallpapers/default.png

splash = false
ipc = on
