# === AUTOSTART ===

# DBUS / SYSTEMD (PRIMEIRO!)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start graphical-session.target

# Polkit / Keyring
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets

# Wallpaper
exec-once = ~/.config/hypr/wallpaper.sh

# Bar / Notifications
exec-once = waybar
exec-once = swaync
exec-once = darkman run

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

# Fix XDG Portal
exec-once = killall xdg-desktop-portal-hyprland
exec-once = killall xdg-desktop-portal
exec-once = sleep 2 && /usr/lib/xdg-desktop-portal-hyprland &
exec-once = sleep 2 && /usr/lib/xdg-desktop-portal &
