####################################################
############# HYPRLAND CONFIG ######################
################ BY TioSEUS ########################
####################################################
# Config principal — apenas carrega os outros arquivos
# Edite o arquivo específico da seção que quer mudar

# === MONITORES ===
source = ~/.config/hypr/monitors.conf

# === WORKSPACES ===
source = ~/.config/hypr/workspaces.conf

# === VARIÁVEIS DE AMBIENTE ===
source = ~/.config/hypr/hyprenv.conf

# === INPUT E VISUAL ===
source = ~/.config/hypr/userconf.conf

# === AUTOSTART ===
source = ~/.config/hypr/autostart.conf

# === WINDOWRULES ===
source = ~/.config/hypr/window.conf

# === KEYBINDS ===
source = ~/.config/hypr/keybinds.conf
