# ==========================================================
# REGRAS DE JANELAS (Window Rules v2)
# ==========================================================

# --- Suas regras do MPV ---
windowrulev2 = float, class:^(mpv)$
windowrulev2 = center, class:^(mpv)$
windowrulev2 = size 1920 1080, class:^(mpv)$

# --- Regras para utilitários do sistema (Abrir flutuando) ---
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = center, class:^(pavucontrol)$
windowrulev2 = size 800 500, class:^(pavucontrol)$

windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(nm-connection-editor)$

# Força a janelinha de senha (Polkit) a abrir flutuando e centralizada
windowrulev2 = float, class:^(polkit-gnome-authentication-agent-1)$
windowrulev2 = center, class:^(polkit-gnome-authentication-agent-1)$

# Ignorar o blur/transparência nos menus de contexto do Chrome/Firefox (Evita bugs visuais)
windowrulev2 = noblur, class:^(google-chrome)$, title:^(?!Google Chrome).*
