# === REGRA DE WORKSPACES POR MONITOR ===

workspace = 1,
workspace = 2,
workspace = 3,
workspace = 4,
workspace = 5,
workspace = 6,
workspace = 7,
workspace = 8,
workspace = 9,

# === SPECIAL WORKSPACE (scratchpad) ===
# Super+Shift+S move janela pro scratchpad
# Super+S abre/fecha o scratchpad
workspace = special:magic, on-created-empty:hyprctl dispatch layoutmsg orientationcycle

# === REGRAS DE WORKSPACE ===
# Aplica gaps especiais quando só tem 1 janela (sem gaps)
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
