### Layout
legacy_layout=0
horizontal=0
font_size=21
background_alpha=0.7
round_corners=8
position=top-left
text_color=FFFFFFFF
gpu_color=00FF00FF
cpu_color=0088FFFF

### GPU (AMD Radeon RX 6750 XT)
custom_text_center=GPU RX 6750 XT
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power
vram
vram_color=FFB400FF

### CPU (Intel i7-9700K)
custom_text_center=CPU i7-9700K
cpu_stats
cpu_temp
cpu_mhz
cpu_power
ram
ram_color=FFB400FF

### Desempenho
custom_text_center=DESEMPENHO
fps
fps_color_change
frame_timing
frametime_color=00FF00FF
hud_no_margin

### Atalhos
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F12
