shell /usr/bin/fish

# Transparência e Janela
blur 1
window_padding_width 15

#Cores
background		#0a0e14
foreground		#b3b1ad
cursor			#007acc
selection_background	#121f35

#Paleta de Cores do Terminal
color0	#01060e
color8	#1a2333
color1	#ff4444
color9	#ff6666
color2	#00cca7
color10	#25edd4
color3	#ffb454
color11	#ffe6b3
color4	#007acc
color12	#33a1ff
color5	#b366ff
color13	#d199ff
color6	#1d809f
color14	#4fc3f7
color7	#b3b1ad
color15	#ffffff
